class SecretTracker : Thinker
{
  int currency;

  SecretTracker Init()
	{
		ChangeStatNum(STAT_STATIC);
		return self;
	}

  static SecretTracker Get()
	{
		ThinkerIterator it = ThinkerIterator.Create("SecretTracker",STAT_STATIC);
		let p = SecretTracker(it.Next());
		if (p == null)
		{
			p = new("SecretTracker").Init();
		}
		return p;
	}

  void UpdateLevelStats()
	{
		currency += (level.found_secrets * 5);
	}
}